[2023-04-01 15:31:29,637] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-04-01T15:31:28.256264+00:00 [queued]>
[2023-04-01 15:31:29,655] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-04-01T15:31:28.256264+00:00 [queued]>
[2023-04-01 15:31:29,658] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-01 15:31:29,659] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-04-01 15:31:29,660] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-01 15:31:29,690] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-01 15:31:28.256264+00:00
[2023-04-01 15:31:29,699] {standard_task_runner.py:52} INFO - Started process 1022 to run task
[2023-04-01 15:31:29,705] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-04-01T15:31:28.256264+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpujqtpite', '--error-file', '/tmp/tmpqh11qviv']
[2023-04-01 15:31:29,708] {standard_task_runner.py:80} INFO - Job 48: Subtask create_table
[2023-04-01 15:31:29,823] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2023-04-01T15:31:28.256264+00:00 [running]> on host 94291ec70be5
[2023-04-01 15:31:29,974] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T15:31:28.256264+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-01T15:31:28.256264+00:00
[2023-04-01 15:31:29,994] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-04-01 15:31:30,003] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
                );
                , parameters: None
[2023-04-01 15:31:30,006] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2023-04-01 15:31:30,031] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230401T153128, start_date=20230401T153129, end_date=20230401T153130
[2023-04-01 15:31:30,091] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-01 15:31:30,183] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
