[2023-04-01 15:43:43,725] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-04-01T15:43:41.819857+00:00 [queued]>
[2023-04-01 15:43:43,743] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2023-04-01T15:43:41.819857+00:00 [queued]>
[2023-04-01 15:43:43,744] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-04-01 15:43:43,745] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-04-01 15:43:43,746] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-04-01 15:43:43,770] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2023-04-01 15:43:41.819857+00:00
[2023-04-01 15:43:43,781] {standard_task_runner.py:52} INFO - Started process 179 to run task
[2023-04-01 15:43:43,787] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2023-04-01T15:43:41.819857+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpts0wd9_k', '--error-file', '/tmp/tmpk15cfyfb']
[2023-04-01 15:43:43,788] {standard_task_runner.py:80} INFO - Job 60: Subtask create_table
[2023-04-01 15:43:43,869] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table manual__2023-04-01T15:43:41.819857+00:00 [running]> on host b3da598da892
[2023-04-01 15:43:43,973] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-01T15:43:41.819857+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-01T15:43:41.819857+00:00
[2023-04-01 15:43:43,988] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2023-04-01 15:43:43,995] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
                );
                , parameters: None
[2023-04-01 15:43:43,997] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2023-04-01 15:43:44,016] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20230401T154341, start_date=20230401T154343, end_date=20230401T154344
[2023-04-01 15:43:44,082] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-04-01 15:43:44,151] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
